# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'iq_bot.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from iqoptionapi.stable_api import IQ_Option
from PyQt5.QtGui import QCursor

import iq_bot_ui

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IqOptionBot = QtWidgets.QMainWindow()
    ui = iq_bot_ui.Ui_IqOptionBot()
    ui.setupUi(IqOptionBot)
    IqOptionBot.show()
    sys.exit(app.exec_())
